### ISSUE TITLE
Incompatibility with Gradle 7.0

### ISSUE THREAD

**Issue by xsveda** [appswithlove/loco-android#18]
Gradle 7.0 requires every property to be marked as input/output or as internal to avoid up-to-date checks:
https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation

Currently when Loco plugin is used with `Gradle 7.0-rc-1` it fails with:
```
A problem was found with the configuration of task ':shared:generic:localisation:updateLoco' (type 'LocoTask').
  - Type 'LocoTask' property 'extension' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Workaround:** Use `Gradle 6.8.3`

**Comment by yannickpulver** [comment]
hi @xsveda 
thanks for the issue, will have a look 👌

**Comment by yannickpulver** [comment]
hi @xsveda 
Version `0.1.10` should be available on `mavenCentral()` soon and should fix this issue. 
Feel free to reopen if the issue still exists ✌️

**Comment by xsveda** [comment]
Thank you very much for quick response!
Unfortunatelly a wrong `@Internal` annotation has been applied.
The `groovy.transform.Internal` has been applied but its should be `org.gradle.api.tasks.Internal` instead - https://docs.gradle.org/7.0-rc-1/javadoc/org/gradle/api/tasks/Internal.html.

Also, can you please check tags for last plugin versions? The `Releases` page does not show them at all.

**Comment by yannickpulver** [comment]
My bad! Should have double checked that before releasing!
I updated the code again for version `0.1.11`. Should be available on mavenCentral soon.

**Comment by xsveda** [comment]
Works great, thanks! 🎉
