### ISSUE TITLE
Could not resolve com.appswithlove.loco:loco:0.1.12

### ISSUE THREAD

**Issue by GuillaumeBourge** [appswithlove/loco-android#21]
Hi thanks for the pull request approval :)

I have an issue since the update to the 1.12 of the lib.
(if i just revert to 1.11 it's ok)

```
> Could not resolve all artifacts for configuration :'classpath'.
   > Could not resolve com.appswithlove.loco:loco:0.1.12.
     Required by:
         project :
      > No matching variant of com.appswithlove.loco:loco:0.1.12 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.appswithlove.loco:loco:0.1.12 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability com.appswithlove.loco:loco:0.1.12 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8  
```  
                
I got the issue on Bitrise and on my gitlabCI with fastlane. On local i have no issue it's fully working.

Is this error does speak to you ? and why it appears with the update of the lib ?

**Comment by yannickpulver** [comment]
Hi @GuillaumeBourge 
Unfortunately I was not able to reproduce it yet. 

According to https://github.com/square/kotlinpoet/issues/999 they suggest it might be something with JDK. Are you currently setting this in your `app/build.gradle`?

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by GuillaumeBourge** [comment]
Hi, Thanks for answer

Yes I am using this compileOptions. 
The only thing that I change is the number version in the root build.gradle :/

It no seems to be so obvious on your link if we look next comments : 
[square/kotlinpoet/pull/1000](https://github.com/square/kotlinpoet/pull/1000)
[JetBrains/markdown/issues/70](https://github.com/JetBrains/markdown/issues/70)

The fact that it is working on my computer and not on CI make me feel it's maybe a cache issue ? i will try to recheck this point.

**Comment by GuillaumeBourge** [comment]
Ok i finally found what was the issue !

I had to switch manually to Java11 on Bitrise : [Bitrise docs](https://devcenter.bitrise.io/infrastructure/virtual-machines/#managing-java-versions)

it will stay a mystery why it's still working with the 0.1.11 of loco. The Cache must do the job...

**Comment by GuillaumeBourge** [comment]
Hi, after the new update of AndroidStudio i got the issue locally too now..
`Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of com.appswithlove.loco:loco:0.1.12 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
  - Variant 'apiElements' capability com.appswithlove.loco:loco:0.1.12 declares a library, packaged as a jar, and its dependencies declared externally:
      - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
  - Variant 'runtimeElements' capability com.appswithlove.loco:loco:0.1.12 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
      - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8`
    

Same issue as here : [issue](https://github.com/cashapp/exhaustive/issues/4)

They fixed it by adding this to the library : https://github.com/cashapp/exhaustive/pull/5/commits/cb6feb4f45c963ce1c84b8733cf4809d12819b02
