### ISSUE TITLE
Possibility to import 2 or more loco file

### ISSUE THREAD

**Issue by GuillaumeBourge** [appswithlove/loco-android#22]
Hi,

I will need to import at least 2 Loco projects into each separated file string_x.xml. There is a way to do it with the current version of the lib ?
If not, have you an idea of how can we add this feature to the lib ? I don't know anything about groovy, but i can try to work on it :)

ex : 
Loco Project A (with api key A)
Loco Project B (with api key B)
etc..

in android project :
res/values/strings_a.xml
res/values/strings_b.xml
etc..

**Comment by yannickpulver** [comment]
Hi @GuillaumeBourge 
I assume we could add this feature pretty easily. For now, the `LocoExtension` class provides all the properties. We could convert this to a list and so provide multiple versions. Like something like that: 

```groovy
class LocoExtension {
    public static final NAME = 'Loco'
    def configs = []
}

class LocoConfig {
    def locoBaseUrl = "https://localise.biz/api/export/locale"
    def apiKey
    def lang = ['en']
    def defLang = 'en'
    def resDir
    def fileName = "strings"
    def placeholderPattern = null
    def hideComments = false
    def tags
    def fallbackLang = null
    def orderByAssetId = false
}
```

which would replace: https://github.com/appswithlove/loco-android/blob/master/src/main/groovy/com/appswithlove/loco/LocoExtension.groovy

I haven't tested it yet, but will try something when I get some time.

**Comment by anthony-fresneau-kiplin** [comment]
Hi @yannickpulver ,
We have done a pull request which add the possibility to add 2 or more loco file.
For a single file, it remains compatible with the actual task updateLoco and the actual configuration syntax
For multiple files, the task updateLocoMultiple is added and a sample configuration block is added in README.md
Best regards,

**Comment by yannickpulver** [comment]
Hi @anthony-fresneau-kiplin 
Great! Thanks for the contribution. I'll have a look at it. :)

**Comment by anthony-fresneau-kiplin** [comment]
Hi @yannickpulver ,
Thanks for the quick merge.
Could you publish a 0.1.13 version including the changes?
Thanks

**Comment by yannickpulver** [comment]
@anthony-fresneau-kiplin @GuillaumeBourge 
Version `0.2.0` should be available soon on `mavenCentral()`. As soon as it appears here:
https://search.maven.org/artifact/com.appswithlove.loco/loco/0.2.0/jar

Thanks for the pull request 👋
