### ISSUE TITLE
strings.xml files on Windows are saved with Windows 1252 Encoding instead of UTF-8

### ISSUE THREAD

**Issue by ast3150** [appswithlove/loco-android#3]
Example Output from file saved with Windows:

```
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <string name="BUTTON_TITLE">Hallo</string>
    <!-- General -->
    <string name="BTN_CONTINUE">Weiter</string>
    <string name="BTN_DONE">Fertig</string>
    <string name="BTN_SKIP">Ãœberspringen</string>
```

Same Output when file is opened manually with UTF-8 encoding:

```
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <string name="BUTTON_TITLE">Hallo</string>
    <!-- General -->
    <string name="BTN_CONTINUE">Weiter</string>
    <string name="BTN_DONE">Fertig</string>
    <string name="BTN_SKIP">Überspringen</string>
```

This causes multiple issues:
- Git merges can break
- Editor tools can't open the file properly because the encoding in the XML header is set as UTF-8
- Strings can get misinterpreted in the apps

To fix this, the encoding probably needs to be explicitly set to UTF-8 when writing to the file, in order to prevent platform differences from causing issues. It is not clear at this point whether the issue is caused by simply running the tool on Windows, or subsequently, for example by opening the file in some editor.

**Comment by yannickpulver** [comment]
Should have been solved with #4
