### ISSUE TITLE
Support for Kotlin DSL plugins block

### ISSUE THREAD

**Issue by Remzoo** [appswithlove/loco-android#37]
Could you please add support for the plugin block (https://developer.android.com/build/migrate-to-kotlin-dsl#convert-plugins-block)? 

Currently, an exception is thrown when adding a plugin.
```
Plugin [id: 'com.appswithlove.loco', version: '0.3.1', apply: false] was not found in any of the following sources:

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.appswithlove.loco', version: '0.3.1', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.appswithlove.loco:com.appswithlove.loco.gradle.plugin:0.3.1')
  Searched in the following repositories:
    Google
    MavenRepo
```

**Comment by yannickpulver** [comment]
Hi @Remzoo 

Thanks for brining that up, wanted to do that a while now. I just submitted a first version to the Gradle Plugin Portal, it's currently in "Pending Approval" state. As soon as that's accepted, it should be available hopefully.

**Comment by yannickpulver** [comment]
@Remzoo Looks like it's available now, let me know if it works

`id("com.appswithlove.loco") version "0.3.1"`
