### ISSUE TITLE
Feature Reqeust: Make strings file metadata optional

### ISSUE THREAD

**Issue by xsveda** [appswithlove/loco-android#6]
On our project we do commit string files to repo and the string file metadata header is often a subject of merge conflicts:

```
<!--
 Loco xml export: Android string resources
 Project: Demo Project
 Release: Working copy
 Locale: en, English
 Exported by: Pavel Sveda
 Exported at: Tue, 14 Jan 2020 16:45:27 +0100
-->
```

We would love to see it optional in gradle plugin configuration and disable it for our project.

**Comment by yannickpulver** [comment]
Hi @xsveda! Thanks for your request. 
I'll have a look, if we can come up with a simple solution.

**Comment by yannickpulver** [comment]
I just uploaded a new release `0.1.1`. With that you should be able to hide the metadata & comments like this:

```java
Loco {
    ...
    hideComments = true
}
```

Let me know if that works out for you 👍

**Comment by xsveda** [comment]
Oh, that was quick! Works great, thank you very much !!! 👍
